# Generated by Django 5.2.6 on 2025-09-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='imagen',
            field=models.TextField(default='prueba'),
            preserve_default=False,
        ),
    ]
