# Generated by Django 5.2.6 on 2025-09-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0002_plato_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='icono',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='seleccionado',
            field=models.BooleanField(default=False),
        ),
    ]
